version: '3'
services:
  app:
    build: .
    depends_on:
      - db   # make sure db starts before app

  db:
    build: db/.
    restart: always
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ROOT_HOST: "%"   # allow root to connect from any host